[package]
name = "imacals-api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "imacals-api"
path = "src/main.rs"

[dependencies]
actix-web = "4.11.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-native-tls", "postgres", "uuid", "chrono", "runtime-async-std-native-tls", "rust_decimal"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
validator = { version = "0.20.0", features = ["derive"] }
actix-web-validator = "7.0.0"
num_cpus = "1.17.0"
tracing = "0.1.41"
actix-cors = "0.7.1"
tracing-actix-web = "0.7.19"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt", "json", "time"] }
actix-extensible-rate-limit = { version = "0.4.0", features = ["dashmap"] }
reqwest = { version = "0.13.3", features = ["json"] }
uuid = { version = "1.18.1", features = ["serde", "v4", "v5"] }
argon2 = "0.5.3"
jsonwebtoken = {version = "10", default-features = false, features = ["rust_crypto"] }
futures = "0.3.31"
futures-util = "0.3"
reqwest-middleware = { version = "0.5.1", features = ["query", "form", "json"] }
reqwest-retry = "0.9.1"
reqwest-tracing = "0.7.0"
actix-multipart = "0.7"
object_store = { version = "0.13", features = ["aws"] }
bytes = "1"
aes-gcm = "0.10"
sha2 = "0.10"
base64 = "0.22"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true