-- Up migration: create_permissions_table
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "permissions"
(
    id   UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR UNIQUE NOT NULL
);

INSERT INTO "permissions" ("name") VALUES
    ('properties.view'),
    ('properties.create'),
    ('properties.update'),
    ('properties.delete'),
    ('properties.sync-images'),
    ('properties.view-comps'),
    ('properties.save-comp'),
    ('properties.view-as-lead'),

    ('renovations.view'),
    ('renovations.view-own'),
    ('renovations.create'),
    ('renovations.update'),
    ('renovations.delete'),
    ('renovations.view-dates'),
    ('renovations.view-phases'),
    ('renovations.view-budget'),
    ('renovations.manage-budget'),
    ('renovations.view-invoices'),
    ('renovations.view-own-invoices'),
    ('renovations.create-invoice'),
    ('renovations.approve-invoice'),
    ('renovations.pay-invoice'),
    ('renovations.view-invoice-history'),
    ('renovations.accept-offer'),
    ('renovations.decline-offer'),
    ('renovations.view-comps'),

    ('calendars.view'),
    ('calendars.create'),
    ('calendars.update'),
    ('calendars.delete'),
    ('calendars.update-scope-of-work'),
    ('calendars.view-labels'),

    ('scopes-of-work.view'),
    ('scopes-of-work.view-phases'),
    ('scopes-of-work.create'),
    ('scopes-of-work.update'),
    ('scopes-of-work.delete'),
    ('scopes-of-work.view-modifications'),

    ('tasks.view'),
    ('tasks.view-own'),
    ('tasks.create'),
    ('tasks.update'),
    ('tasks.complete'),
    ('tasks.delete'),
    ('tasks.undo'),
    ('tasks.upload-pictures'),

    ('contractors.view'),
    ('contractors.create'),
    ('contractors.update'),
    ('contractors.delete'),
    ('contractors.invite'),
    ('contractors.view-invites'),
    ('contractors.create-invite'),
    ('contractors.accept-invite'),
    ('contractors.decline-invite'),

    ('invoices.view'),
    ('invoices.view-own'),
    ('invoices.create'),
    ('invoices.update'),
    ('invoices.approve'),
    ('invoices.reject'),
    ('invoices.pay'),
    ('invoices.view-history'),
    ('invoices.view-grouped'),

    ('permits.view'),
    ('permits.create'),
    ('permits.update'),
    ('permits.delete'),
    ('permits.upload'),

    ('change-orders.view'),
    ('change-orders.create'),
    ('change-orders.update'),
    ('change-orders.approve'),
    ('change-orders.delete'),
    ('change-orders.view-phased'),

    ('budget-items.view'),
    ('budget-items.create'),
    ('budget-items.update'),
    ('budget-items.delete'),
    ('budget-items.find'),

    ('room-photos.view'),
    ('room-photos.upload'),
    ('room-photos.delete'),

    ('leads.view'),
    ('leads.create'),
    ('leads.update'),
    ('leads.delete'),
    ('leads.discard'),
    ('leads.view-status'),

    ('offers.view'),
    ('offers.create'),
    ('offers.update'),
    ('offers.delete'),
    ('offers.view-status'),
    ('offers.view-modifications'),

    ('bids.view'),
    ('bids.create'),
    ('bids.update'),
    ('bids.delete'),
    ('bids.assign'),

    ('contracts.view'),
    ('contracts.view-all'),
    ('contracts.create'),
    ('contracts.update'),
    ('contracts.delete'),
    ('contracts.view-templates'),
    ('contracts.create-template'),
    ('contracts.update-template'),
    ('contracts.delete-template'),

    ('maps.view'),
    ('maps.create'),
    ('maps.update'),
    ('maps.delete'),
    ('maps.view-untagged-properties'),

    ('polygons.create'),
    ('polygons.update'),
    ('polygons.delete'),
    ('polygons.add-neighbor'),
    ('polygons.delete-neighbor'),
    ('polygons.update-zone'),
    ('polygons.delete-zone'),

    ('polygon-zones.view'),
    ('polygon-zones.create'),
    ('polygon-zones.update'),
    ('polygon-zones.delete'),

    ('marketing.view'),
    ('marketing.generate-content'),
    ('marketing.preview'),
    ('marketing.send-email'),
    ('marketing.view-queue'),
    ('marketing.manage-queue'),

    ('files.view'),
    ('files.upload'),
    ('files.download'),

    ('users.view'),
    ('users.create'),
    ('users.update'),
    ('users.delete'),
    ('users.manage-roles'),
    ('users.manage-permissions'),

    ('roles.view'),
    ('roles.create'),
    ('roles.update'),
    ('roles.delete'),

    ('banks.verification-required'),
    ('banks.view'),
    ('banks.view-own'),
    ('banks.create'),
    ('banks.update'),
    ('banks.delete'),
    ('banks.verify'),
    ('banks.create-customer'),
    ('banks.generate-session'),
    ('banks.view-status'),

    ('listings.view'),
    ('listings.create'),
    ('listings.update'),
    ('listings.delete'),

    ('notes.view'),
    ('notes.create'),
    ('notes.update'),
    ('notes.delete'),

    ('flows.view'),
    ('flows.create'),
    ('flows.update'),
    ('flows.delete'),

    ('datatables.view'),
    ('datatables.create'),
    ('datatables.update'),
    ('datatables.delete'),

    ('preferences.view'),
    ('preferences.update'),

    ('feedback.view'),
    ('feedback.create'),
    ('feedback.update'),
    ('feedback.delete'),

    ('domains.view'),
    ('domains.create'),
    ('domains.update'),
    ('domains.delete'),

    ('dashboard.view'),
    ('dashboard.view-analytics'),

    ('webhooks.manage'),
    ('ai.use'),
    ('request-logs.view'),

    ('config.view'),
    ('config.update'),

    ('calendar-titles.view'),
    ('calendar-titles.create'),
    ('calendar-titles.update'),
    ('calendar-titles.delete'),

    ('financial-documents.view'),
    ('financial-documents.create'),
    ('financial-documents.update'),
    ('financial-documents.delete'),
    ('financial-documents.delete-files'),

    ('email-tracking.view'),

    ('micro-flows.view'),
    ('micro-flows.create'),
    ('micro-flows.update'),
    ('micro-flows.delete'),

    ('groups.view'),
    ('groups.create'),
    ('groups.update'),
    ('groups.delete'),

    ('pdf.generate'),
    ('static-maps.generate'),

    ('integrations.view'),
    ('integrations.create'),
    ('integrations.update'),
    ('integrations.delete'),

    ('attributes.view'),
    ('attributes.create'),
    ('attributes.update'),
    ('attributes.delete');
